version: 2

sources:
  - name: olist
    database: olistdb
    schema: public
    tables:
      - name: customers
      - name: orders
      - name: order_items
      - name: products
      - name: sellers
      - name: payments
