
CREATE ROLE analyst LOGIN PASSWORD 'analyst1';


CREATE ROLE app_user LOGIN PASSWORD 'app1';



REVOKE ALL ON DATABASE olistdb FROM PUBLIC;
REVOKE ALL ON SCHEMA public FROM PUBLIC;



GRANT CONNECT ON DATABASE olistdb TO analyst;
GRANT USAGE ON SCHEMA public TO analyst;


GRANT SELECT ON ALL TABLES IN SCHEMA public TO analyst;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO analyst;



GRANT CONNECT ON DATABASE olistdb TO app_user;
GRANT USAGE, CREATE ON SCHEMA public TO app_user;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO app_user;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
